### PR TITLE
Update code to match with lecture and exercise

### PR DESCRIPTION
**Pull request by cveneziani**
- Move app.rb to lib/ folder since it's what they have in their cookbook exercise
- Require task model from the repository instead of the controller
- Repository should be singular

### CODE REVIEW

**Comment by alex-felix** [comment]
No need to require task in repo right?

**Comment by alex-felix** [comment]
And we need it in the controller

**Comment by cveneziani** [comment]
We need to require `task` somewhere and I believe it makes more sense to require it from the repository because it's the class that is in charge of managing the tasks.

And in the Cookbook challenge, we also require`recipe` from the `cookbook` repository.

What do you think?

**Comment by alex-felix** [comment]
we require it in the cookbook solution because we need the class when recreating the recipe instance when reading from the csv and use `Recipe.new`

we also have the require task in the cookbook where we do a `Recipe.new`

we need to have the require wherever we use the class explicitly and not depend on the order of required files that might cause weird issues

let's go back to having a require in the controller and not in the cookbook if that is ok with you

**Comment by cveneziani** [comment]
By requiring classes wherever we use them, it would mean for instance, for the food delivery challenge that we would have this:

- meal repo loading Meal model
- meals controller also loading Meal model
- custome repository loading Customer model
- customers controller also loading Customer model
- employee repo loading Employee model
- session controller also loading Employee model
- order repo loading Order, Meal, Customer and Employee models and repositories
- order controller also loading Order, Meal, Customer and Employee models and repositories

Don't you agree this would be too much?
I have the feeling that we'd rather teach them the rails way.

So, I'd say:

1. Either we can make the statement that the repository will be in charge of loading its related model, the one (and only one) it is managing.
2. Or the app.rb could be in charge of loading all the models since it's the entry point of the app.

What do you think?

**Comment by ssaunier** [comment]
I'd go with option 2. PR + lectures need to be updated.
I so your discussions on Food Delivery, I'm fine with going with an hash argument.

**Comment by cveneziani** [comment]
I'll update this PR regarding the loading of the model.

**Comment by cveneziani** [comment]
Fixed.

**Comment by ssaunier** [comment]
🙏

**Pull request merged**
